site_name: "Grid Meta Documentation"
site_url: https://grid-atlas.github.io/grid-meta
repo_url: https://github.com/Grid-Atlas/grid-meta
theme: 
  name: material
  logo: assets/logo.png
  font: 
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: "material/brightness-7"
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: "material/brightness-5"
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - admonition
  - codehilite
  - md_in_html
  - "pymdownx.details"
  - "pymdownx.superfences"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Getting Started:
      - Getting Started: index.md
      - Developer Guides: getting-started/dev-guides.md
  - Dehydration Schema:
      - Metadata : schemas/index.md
extra: 
  version:
    provider: mike
    default: latest